//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranca
    {
        public int Id { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<StatusCobrancaEnum> Status { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
