//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convenio
    {
        public Convenio()
        {
            this.Pacientes = new HashSet<Paciente>();
            this.Telefones = new HashSet<Telefone>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public Nullable<long> NumeroCartao { get; set; }
        public Nullable<TipoPlanoSaudeEnum> TipoPlanoSaude { get; set; }
    
        public virtual ICollection<Paciente> Pacientes { get; set; }
        public virtual ICollection<Telefone> Telefones { get; set; }
    }
}
