//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Pessoa
    {
        public Pessoa()
        {
            this.Documentos = new HashSet<Documento>();
            this.Telefones = new HashSet<Telefone>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Nascimento { get; set; }
        public string Senha { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string Naturalidade { get; set; }
        public string Nacionalidade { get; set; }
        public Nullable<SexoEnum> Sexo { get; set; }
        public Nullable<EstadoCivilEnum> EstadoCivil { get; set; }
    
        public virtual ICollection<Documento> Documentos { get; set; }
        public virtual Endereco Endereco { get; set; }
        public virtual ICollection<Telefone> Telefones { get; set; }
    }
}
