//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profissional : Pessoa
    {
        public Profissional()
        {
            this.Especialidade = new HashSet<Especialidade>();
            this.Consultas = new HashSet<Consulta>();
            this.Reservas = new HashSet<Reserva>();
        }
    
        public Nullable<int> NumeroConselho { get; set; }
    
        public virtual ICollection<Especialidade> Especialidade { get; set; }
        public virtual ICollection<Consulta> Consultas { get; set; }
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
