//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    
    public enum StatusCobrancaEnum : int
    {
        EmAberto = 0,
        EmNegociacao = 1,
        Cancelada = 2
    }
}
