//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int Id { get; set; }
        public Nullable<short> DDI { get; set; }
        public Nullable<short> DDD { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> Ramal { get; set; }
        public Nullable<TipoTelefoneEnum> Tipo { get; set; }
        public Nullable<int> PessoaId { get; set; }
        public Nullable<int> ConvenioId { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Convenio Convenio { get; set; }
    }
}
