//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    
    public enum TipoMoradiaEnum : int
    {
        Casa = 0,
        Apartamento = 1,
        Flat = 2,
        Kitnet = 3,
        Conjugado = 4
    }
}
